[package]
name = "city_by_altitude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
actix-files = "0.6.0"

